function sin(x){return Math.sin(x)}
function cos(x){return Math.cos(x)}
function tan(x){return Math.tan(x)}
function sec(x){return Math.sec(x)}
function csc(x){return Math.csc(x)}
function cot(x){return Math.cot(x)}
function round(x){return Math.round(x)}
function floor(x){return Math.floor(x)}
function pow(x,y){return Math.pow(x,y)}
function sign(x){return Math.sign(x)}
function ciel(x){return Math.ceil(x)}
function exp(x){return Math.exp(x)}
function log(x){return Math.log(x)}
function max(x,y){return Math.max(x,y)}
function min(x,y){return Math.min(x,y)}
function sqrt(x){return Math.sqrt(x)}
function trunc(x){return Math.trunc(x)}
function cbrt(x){return Math.cbrt(x)}
function abs(x){return Math.abs(x)}
function cosh(x){return Math.cosh(x)}
function sinh(x){return Math.sinh(x)}
function tanh(x){return Math.tanh(x)}
function random(){return Math.random()}
function randf_range(x,y){return Math.random()*Math.max(x,y)-Math.min(x,y)}
function rand_range(x,y){return Math.random()*Math.max(x,y)-Math.min(x,y)}
function randi_range(x,y){return Math.round(Math.random()*Math.max(x,y)-Math.min(x,y))}